services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-pps
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pps
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8
    container_name: pps-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pps
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
